annotate/urls.py
from django.urls import path

from . import views

app_name = 'annotate'
urlpatterns = [
    path('', views.index, name='index'),


    # sidenav zone
    path('items/', views.ItemIndexView.as_view(), name='item_index'),
    path('items_topics/', views.ItemIndexTopicsView.as_view(), name='item_topics_index'),
    path('triples/', views.TripleIndexView.as_view(), name='triples_index'),
    path('sentences/', views.SentenceIndexView.as_view(), name='sentence_index'),
    path('tweets/', views.TweetIndexView.as_view(), name='tweet_index'),

    path('items0/', views.ItemsPendingAcceptanceIndexView.as_view(), name='item_index0'),
    path('items2/', views.ItemsPendingSentenceSplitValidationIndexView.as_view(), name='item_index2'),
    path('items4/', views.ItemsPendingSentenceCWValidationIndexView.as_view(), name='item_index4'),
    path('items5/', views.ItemsWithSentenceCWAnnotationIndexView.as_view(), name='item_index5'),
    path('items6/', views.ItemsPendingSentenceSPOValidationIndexView.as_view(), name='item_index6'),
    path('items7/', views.ItemsPendingSentenceFCValidationIndexView.as_view(), name='item_index7'),
    path('items8/', views.ItemsWithSentenceFCAnnotationIndexView.as_view(), name='item_index8'),
    path('items9/', views.ItemsWithFCAnnotationIndexView.as_view(), name='item_index9'),

    path('items/create/', views.item_create, name='item_create'),
    path('items0/<int:pk>/', views.ItemDetailView0.as_view(), name='item_detail0'),
    path('items/<int:pk>/', views.ItemDetailView.as_view(), name='item_detail'),
    path('items/<int:pk>/update/', views.item_update, name='item_update'),
    path('items/<int:pk>/delete/', views.ItemDelete.as_view(), name='item_delete'),

    path('items_topics/<int:pk>/update/', views.item_topics_update, name='item_topics_update'),

    path('triples/<int:pk>/update/', views.triple_update, name='triple_update'),

    path('extitems0/', views.ExternalItemsPendingAcceptanceIndexView.as_view(), name='ext_item_index0'),
    path('extitems1/', views.ExternalItemsPendingSentenceSplitIndexView.as_view(), name='ext_item_index1'),
    path('extitems3/', views.ExternalItemsPendingCWClassificationIndexView.as_view(), name='ext_item_index3'),
    path('extitems5/', views.ExternalItemsWithSentenceCWAnnotationIndexView.as_view(), name='ext_item_index5'),
    path('extitems7/', views.ExternalItemsPendingFCClassificationIndexView.as_view(), name='ext_item_index7'),
    path('extitems8/', views.ExternalItemsWithFCClassificationIndexView.as_view(), name='ext_item_index8'),
    path('extitems9/', views.ExternalItemsWithFCAnnotationIndexView.as_view(), name='ext_item_index9'),

    path('sentences2/', views.SentencesPendingSplitValidationIndexView.as_view(), name='sentence_index2'),
    path('sentences4/', views.SentencesPendingCWValidationIndexView.as_view(), name='sentence_index4'),
    path('sentences5/', views.SentencesWithCWAnnotationIndexView.as_view(), name='sentence_index5'),
    path('sentences6/', views.SentencesPendingSPOValidationIndexView.as_view(), name='cw_sentence_index6'),
    path('sentences7/', views.SentencesPendingFCValidationIndexView.as_view(), name='cw_sentence_index7'),
    path('sentences8/', views.SentencesWithFCAnnotationSentenceIndexView.as_view(), name='cw_sentence_index8'),
    path('sentences9/', views.SentencesWithItemFCAnnotationSentenceIndexView.as_view(), name='cw_sentence_index9'),

    path('sentences/create/', views.sentence_create, name='sentence_create'),
    path('sentences/<int:pk>/', views.SentenceDetailView.as_view(), name='sentence_detail'),
    path('sentences/<int:pk>/update/', views.sentence_update, name='sentence_update'),
    path('sentences/<int:pk>/duplicate/', views.sentence_duplicate, name='sentence_duplicate'),
    path('sentences/<int:pk>/delete/', views.SentenceDelete.as_view(), name='sentence_delete'),

    path('cwsentences/<int:pk>/', views.CWSentenceDetailView.as_view(), name='cw_sentence_detail'),
    path('cwsentences/<int:pk>/update/', views.cw_sentence_update, name='cw_sentence_update'),
    path('configuration/<int:pk>/update/', views.configuration_update, name='configuration_update'),

    path('extsentences3/', views.ExternalSentencesPendingCWClassificationIndexView.as_view(), name='ext_sentence_index3'),
    path('extsentences5/', views.ExternalSentencesWithCWAnnotationIndexView.as_view(), name='ext_sentence_index5'),
    path('extsentences7/', views.ExternalSentencesPendingFCClassificationIndexView.as_view(), name='ext_sentence_index7'),
    path('extsentences8/', views.ExternalSentencesWithFCClassificationIndexView.as_view(), name='ext_sentence_index8'),
    path('extsentences9/', views.ExternalSentencesWithItemFCAnnotationSentenceIndexView.as_view(), name='ext_cw_sentence_index9'),

    path('tweets0/', views.TweetsPendingAcceptanceIndexView.as_view(), name='tweet_index'),
    path('tweets4/', views.TweetsPendingCWValidationIndexView.as_view(), name='tweet_index'),
    path('tweets5/', views.TweetsWithCWAnnotationIndexView.as_view(), name='tweet_index'),
    path('tweets7/', views.TweetsPendingFCValidationIndexView.as_view(), name='tweet_index'),
    path('tweets8/', views.TweetsWithFCAnnotationIndexView.as_view(), name='tweet_index'),

    path('tweets/<int:pk>/', views.TweetDetailView.as_view(), name='tweet_detail'),

    path('api_v1/item/<int:pk>/', views.APIItemDetail.as_view(), name='apiv1_item_detail'),
    path('api_v1/sentence/<int:pk>/', views.APISentenceDetail.as_view(), name='apiv1_sentence_detail'),

]

site1/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('annotate/', include('annotate.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

admin.autodiscover()
admin.site.enable_nav_sidebar = False

annotate/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.forms import ModelForm
from django.forms import CharField
from django.forms import TextInput, Textarea
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from datetime import datetime

from rest_framework.views import APIView
from rest_framework.response import Response

from .models import Item, Sentence, Tweet, TwitterUser, Configuration, Triple
from .serializers import ItemSerializer, SentenceSerializer



LIST_VIEW_PAGINATE_BY = 39


# --------------------------
# --- dashboard counters ---
# --------------------------

def index(request):
    # View function for home page

    configuration_instance = Configuration.objects.get(configuration_pk=0)
    configuration_show_tweets = configuration_instance.show_tweets
    configuration_environment_type = configuration_instance.environment_type


    # dashboard counters

    items_pending_acceptance = Item.objects.filter(review_level=0, skip_validations=False).count()
    items_pending_sentence_split_validation = Item.objects.filter(review_level=2, skip_validations=False).count()
    items_pending_sentence_cw_validation = Item.objects.filter(review_level=4, skip_validations=False).count()
    items_with_sentence_cw_annotation = Item.objects.filter(review_level=5, skip_validations=False).count()
    items_pending_sentence_spo_validation = Item.objects.filter(review_level=6, skip_validations=False).count()
    items_pending_sentence_fc_validation = Item.objects.filter(review_level=7, skip_validations=False).count()
    items_with_sentence_fc_annotation = Item.objects.filter(review_level=8, skip_validations=False).count()
    items_with_fc_annotation = Item.objects.filter(review_level=9, skip_validations=False).count()

    external_items_pending_acceptance = Item.objects.filter(review_level=0, skip_validations=True).count()
    external_items_pending_sentence_split = Item.objects.filter(review_level=1, skip_validations=True).count()
    external_items_pending_cw_classification = Item.objects.filter(review_level=3, skip_validations=True).count()
    external_items_with_sentence_cw_annotation = Item.objects.filter(review_level=5, skip_validations=True).count()
    external_items_pending_fc_classification = Item.objects.filter(review_level=7, skip_validations=True).count()
    external_items_with_fc_classification = Item.objects.filter(review_level=8, skip_validations=True).count()
    external_items_with_fc_annotation = Item.objects.filter(review_level=9, skip_validations=True).count()

    total_items = Item.objects.count()

    sentences_pending_split_validation = Sentence.objects.filter(review_level=2, skip_validations=False).count()
    sentences_pending_cw_validation = Sentence.objects.filter(review_level=4, skip_validations=False).count()
    sentences_with_cw_annotation = Sentence.objects.filter(review_level=5, skip_validations=False).count()
    sentences_pending_spo_validation = Sentence.objects.filter(review_level=6, skip_validations=False).count()
    sentences_pending_fc_validation = Sentence.objects.filter(review_level=7, skip_validations=False).count()
    sentences_with_fc_annotation = Sentence.objects.filter(review_level=8, skip_validations=False).count()
    sentences_with_item_fc_annotation = Sentence.objects.filter(review_level=9, skip_validations=False).count()

    external_sentences_pending_cw_classification = Sentence.objects.filter(review_level=3, skip_validations=True).count()
    external_sentences_with_cw_annotation = Sentence.objects.filter(review_level=5, skip_validations=True).count()
    external_sentences_pending_fc_classification = Sentence.objects.filter(review_level=7, skip_validations=True).count()
    external_sentences_with_fc_classification = Sentence.objects.filter(review_level=8, skip_validations=True).count()
    external_sentences_with_item_fc_annotation = Sentence.objects.filter(review_level=9, skip_validations=True).count()

    total_sentences = Sentence.objects.count()

    tweets_pending_acceptance = Tweet.objects.filter(review_level=0).count()
    tweets_pending_cw_validation = Tweet.objects.filter(review_level=4).count()
    tweets_with_cw_annotation = Tweet.objects.filter(review_level=5).count()
    tweets_pending_fc_validation = Tweet.objects.filter(review_level=7).count()
    tweets_with_fc_annotation = Tweet.objects.filter(review_level=8).count()

    total_tweets = Tweet.objects.count()

    total_twitter_users = TwitterUser.objects.count()

    context = {
        'configuration_show_tweets': configuration_show_tweets,
        'configuration_environment_type': configuration_environment_type,

        'items_pending_acceptance': items_pending_acceptance,
        'items_pending_sentence_split_validation': items_pending_sentence_split_validation,
        'items_pending_sentence_cw_validation': items_pending_sentence_cw_validation,
        'items_with_sentence_cw_annotation': items_with_sentence_cw_annotation,
        'items_pending_sentence_spo_validation': items_pending_sentence_spo_validation,
        'items_pending_sentence_fc_validation': items_pending_sentence_fc_validation,
        'items_with_sentence_fc_annotation': items_with_sentence_fc_annotation,
        'items_with_fc_annotation': items_with_fc_annotation,
        'external_items_pending_acceptance': external_items_pending_acceptance,
        'external_items_pending_sentence_split': external_items_pending_sentence_split,
        'external_items_pending_cw_classification': external_items_pending_cw_classification,
        'external_items_with_sentence_cw_annotation': external_items_with_sentence_cw_annotation,
        'external_items_pending_fc_classification': external_items_pending_fc_classification,
        'external_items_with_fc_classification': external_items_with_fc_classification,
        'external_items_with_fc_annotation': external_items_with_fc_annotation,
        'total_items': total_items,

        'sentences_pending_split_validation': sentences_pending_split_validation,
        'sentences_pending_cw_validation': sentences_pending_cw_validation,
        'sentences_with_cw_annotation': sentences_with_cw_annotation,
        'sentences_pending_spo_validation': sentences_pending_spo_validation,
        'sentences_pending_fc_validation': sentences_pending_fc_validation,
        'sentences_with_fc_annotation': sentences_with_fc_annotation,
        'sentences_with_item_fc_annotation': sentences_with_item_fc_annotation,
        'external_sentences_pending_cw_classification': external_sentences_pending_cw_classification,
        'external_sentences_with_cw_annotation': external_sentences_with_cw_annotation,
        'external_sentences_pending_fc_classification': external_sentences_pending_fc_classification,
        'external_sentences_with_fc_classification': external_sentences_with_fc_classification,
        'external_sentences_with_item_fc_annotation': external_sentences_with_item_fc_annotation,
        'total_sentences': total_sentences,

        'tweets_pending_acceptance': tweets_pending_acceptance,
        'tweets_pending_cw_validation': tweets_pending_cw_validation,
        'tweets_with_cw_annotation': tweets_with_cw_annotation,
        'tweets_pending_fc_validation': tweets_pending_fc_validation,
        'tweets_with_fc_annotation': tweets_with_fc_annotation,
        'total_tweets': total_tweets,

        'total_twitter_users': total_twitter_users,
    }

    return render(request, 'annotate/index.html', context=context)

# -----------------------
# --- Item list views ---
# -----------------------


class ItemIndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'annotate/item_index.html'
    context_object_name = 'item_list'
    paginate_by = LIST_VIEW_PAGINATE_BY

    def get_queryset(self):
        return Item.objects.order_by('id')


class ItemsPendingAcceptanceIndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'annotate/item_index.html'
    context_object_name = 'item_list'
    paginate_by = LIST_VIEW_PAGINATE_BY

    def get_queryset(self):
        return Item.objects.filter(review_level=0, skip_validations=False).order_by('-id')


class ExternalItemsPendingAcceptanceIndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'annotate/item_index.html'
    context_object_name = 'item_list'
    paginate_by = LIST_VIEW_PAGINATE_BY

    def get_queryset(self):
        return Item.objects.filter(review_level=0, skip_validations=True).order_by('-id')


class ItemsPendingSentenceSplitValidationIndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'annotate/item_index.html'
    context_object_name = 'item_list'
    paginate_by = LIST_VIEW_PAGINATE_BY

    def get_queryset(self):
        return Item.objects.filter(review_level=2).order_by('id')


class ItemsPendingSentenceCWValidationIndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'annotate/item_index.html'
    context_object_name = 'item_list'
    paginate_by = LIST_VIEW_PAGINATE_BY

    def get_queryset(self):
        return Item.objects.filter(review_level=4).order_by('id')

class ExternalItemsPendingSentenceSplitIndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'annotate/item_index.html'
    context_object_name = 'item_list'
    paginate_by = LIST_VIEW_PAGINATE_BY

    def get_queryset(self):
        return Item.objects.filter(review_level=1, skip_validations=True).order_by('id')

class ExternalItemsPendingCWClassificationIndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'annotate/item_index.html'
    context_object_name = 'item_list'
    paginate_by = LIST_VIEW_PAGINATE_BY

    def get_queryset(self):

annotate/templates/annotate/item_create_form.html
{% extends "annotate/base_generic.html" %}
{% load verbose_names %}

{% block sidebar %}
<a href="{% url 'annotate:index' %}">< Dashboard</a>
{% endblock %}

{% block page_title %}
New Item
{% endblock %}

{% block content %}
<!-- <ul> -->
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="Add Item" />
  </form>
<!-- </ul> -->
{% endblock %}

annotate/templates/annotate/item_detail_0.html
{% extends "annotate/base_generic.html" %}
{% load verbose_names %}

{% block sidebar %}
<a href="{% url 'annotate:index' %}">< Dashboard</a>

{% if item.skip_validations %}
  {% if item.review_level == 0 %}
    <a href="{% url 'annotate:ext_item_index0' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 5 %}
    <a href="{% url 'annotate:ext_item_index5' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 9 %}
    <a href="{% url 'annotate:ext_item_index9' %}">< Items</a>
  {% endif %}
{% else %}
  {% if item.review_level == 0 %}
    <a href="{% url 'annotate:item_index0' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 2 %}
    <a href="{% url 'annotate:item_index2' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 4 %}
    <a href="{% url 'annotate:item_index4' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 5 %}
    <a href="{% url 'annotate:item_index5' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 6 %}
    <a href="{% url 'annotate:item_index6' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 7 %}
    <a href="{% url 'annotate:item_index7' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 8 %}
    <a href="{% url 'annotate:item_index0' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 9 %}
    <a href="{% url 'annotate:item_index9' %}">< Items</a>
  {% endif %}
{% endif %}

<a href="{% url 'annotate:item_update' item.id %}">> Edit</a>
<a href="{% url 'annotate:item_delete' item.id %}">> Delete</a>
{% endblock %}

{% block page_title %}
Item Detail
{% endblock %}

{% block content %}
<table class="detail_table">
  <colgroup>
    <col width="15%" />
    <col width="100%" />
  </colgroup>

  <tr><td><strong>{% get_verbose_field_name item "title" %}:</strong></td><td>{{ item.title }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "type" %}:</strong></td><td>{{ item.type }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "abstract" %}:</strong></td><td>{{ item.abstract }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "publication_date" %}:</strong></td><td>{{ item.publication_date }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "source_entity" %}:</strong></td><td>{{ item.source_entity }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "review_entity" %}:</strong></td><td>{{ item.review_entity }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "review_url" %}:</strong></td><td><a href="{{ item.review_url }}" target="_blank">{{ item.review_url }}</a></td></tr>
  <tr><td><strong>{% get_verbose_field_name item "claim" %}:</strong></td><td>{{ item.claim }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "original_rating" %}:</strong></td><td>{{ item.original_rating }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "rating" %}:</strong></td><td>{{ item.rating }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "item_class" %}:</strong></td><td>{{ item.item_class }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "item_class_4" %}:</strong></td><td>{{ item.item_class_4 }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "item_class_auto" %}:</strong></td><td>{{ item.item_class_auto }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "item_class_4_auto" %}:</strong></td><td>{{ item.item_class_4_auto }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "crawl_date" %}:</strong></td><td>{{ item.crawl_date }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "url" %}:</strong></td><td><a href="{{ item.url }}" target="_blank">{{ item.url }}</a></td></tr>
  <tr><td><strong>{% get_verbose_field_name item "url_2" %}:</strong></td><td><a href="{{ item.url_2 }}" target="_blank">{{ item.url_2 }}</a></td></tr>
  <tr><td><strong>{% get_verbose_field_name item "text" %}:</strong></td><td>{{ item.text }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "review_summary" %}:</strong></td><td>{{ item.review_summary }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "review_level" %}:</strong></td><td>{{ item.review_level }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "url_ok" %}:</strong></td><td>{{ item.url_ok }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "no_health_useless" %}:</strong></td><td>{{ item.no_health_useless }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "needs_revision" %}:</strong></td><td>{{ item.needs_revision }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "instance_type" %}:</strong></td><td>{{ item.instance_type }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "main_topic" %}:</strong></td><td>{{ item.main_topic }}</td></tr>
  <tr><td><strong>{% get_verbose_field_name item "main_claim" %}:</strong></td><td>{{ item.main_claim }}</td></tr>

</table>
{% endblock %}

annotate/templates/annotate/item_form.html
{% extends "annotate/base_generic.html" %}
{% load verbose_names %}

{% block sidebar %}
<a href="{% url 'annotate:index' %}">< Dashboard</a>

{% if item.skip_validations %}
  {% if item.review_level == 0 %}
    <a href="{% url 'annotate:ext_item_index0' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 5 %}
    <a href="{% url 'annotate:ext_item_index5' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 9 %}
    <a href="{% url 'annotate:ext_item_index9' %}">< Items</a>
  {% endif %}
{% else %}
  {% if item.review_level == 0 %}
    <a href="{% url 'annotate:item_index0' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 2 %}
    <a href="{% url 'annotate:item_index2' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 4 %}
    <a href="{% url 'annotate:item_index4' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 5 %}
    <a href="{% url 'annotate:item_index5' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 6 %}
    <a href="{% url 'annotate:item_index6' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 7 %}
    <a href="{% url 'annotate:item_index7' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 8 %}
    <a href="{% url 'annotate:item_index0' %}">< Items</a>
  {% endif %}
  {% if item.review_level == 9 %}
    <a href="{% url 'annotate:item_index9' %}">< Items</a>
  {% endif %}
{% endif %}
{% endblock %}

{% block page_title %}
Edit Item
{% endblock %}

{% block content %}
<!-- <ul> -->
<form action="" method="post">
    {% csrf_token %}

    <li><p class="form_title">{% get_verbose_field_name item "title" %}</p></li>
    <li>{{ form.title }}</li>
    <li>{{ form.title.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "claim" %}</p></li>
    <li>{{ item.claim }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "source_entity" %}</p></li>
    <li>{{ form.source_entity }}</li>
    <li>{{ form.source_entity.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "url" %}</p></li>
    <li>{{ form.url }}</li>
    <li>{{ form.url.errors.label_tag }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "url_2" %}</p></li>
    <li>{{ form.url_2 }}</li>
    <li>{{ form.url_2.errors.label_tag }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "review_url" %}</p></li>
    <li><a href="{{ item.review_url }}" target="_blank">{{ item.review_url }}</a></li>

    <li><p class="form_title">{% get_verbose_field_name item "text" %}</p></li>
    <li>{{ form.text }}</li>
    <li>{{ form.text.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "item_class" %}</p></li>
    <li>{{ form.item_class }}</li>
    <li>{{ form.item_class.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "item_class_4" %}</p></li>
    <li>{{ form.item_class_4 }}</li>
    <li>{{ form.item_class_4.errors }}</li>

    <li>
      <table class="columns_table">
        <colgroup>
          <col width="50%" />
          <col width="50%" />
        </colgroup>
        <tr>
          <td><p class="form_title">{% get_verbose_field_name item "item_class_auto" %}</p></td>
          <td><p class="form_title">{% get_verbose_field_name item "item_class_4_auto" %}</p></td>
        </tr>
        <tr>
          <td>{{ item.item_class_auto }}</td>
          <td>{{ item.item_class_4_auto }}</td>
        </tr>
      </table>
    </li>

    <li><p class="form_title">{% get_verbose_field_name item "url_ok" %}</p></li>
    <li>{{ form.url_ok }}</li>
    <li>{{ form.url_ok.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "no_health_useless" %}</p></li>
    <li>{{ form.no_health_useless }}</li>
    <li>{{ form.no_health_useless.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "review_level" %}</p></li>
    <li>{{ form.review_level }}</li>
    <li>{{ form.review_level.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "skip_validations" %}</p></li>
    <li>{{ form.skip_validations }}</li>
    <li>{{ form.skip_validations.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "instance_type" %}</p></li>
    <li>{{ form.instance_type }}</li>
    <li>{{ form.instance_type.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "needs_revision" %}</p></li>
    <li>{{ form.needs_revision }}</li>
    <li>{{ form.needs_revision.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "revision_reason" %}</p></li>
    <li>{{ form.revision_reason }}</li>
    <li>{{ form.revision_reason.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "main_topic" %}</p></li>
    <li>{{ form.main_topic }}</li>
    <li>{{ form.main_topic.errors }}</li>

    <li><p class="form_title">{% get_verbose_field_name item "main_claim" %}</p></li>
    <li>{{ form.main_claim }}</li>
    <li>{{ form.main_claim.errors }}</li>


    <li>
      <input type="submit" value="Update Item">
    </li>
  </form>
<!-- </ul> -->
{% endblock %}